### ISSUE TITLE
Release 0.5.1 breaks update and install with yay

### ISSUE THREAD

**Issue by PierrickF** [nimaaskarian/c3#1]
Hi,

First, thanks; I've been using c3 for a few days and will stick with it. :smile: 

# Issue
From a working c3 install (which I presume was release 0.5.0), and upon running `yay` to update c3, or `yay -S c3` to install c3, yay exits with exit status 1.
It seems that c3's release 0.5.1 cannot pass the md5 validity check.

# Expected behavior
c3 can be updated and installed with yay.

# Reproducing the error
* I first encountered the issue while trying to update c3 through yay.
* I still encounter the same error when trying to re-install c3 with yay.

# Error message
```
> yay -S c3
AUR Explicit (1): c3-0.5.1-1
:: PKGBUILD up to date, skipping download: c3
  1 c3                                       (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 c3                                       (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: c3 0.5.1-1 (Mon 18 Mar 2024 07:35:40 PM CET)
==> Retrieving sources...
  -> Found c3.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    c3.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/pierrick/.cache/yay/c3
	 context: exit status 1
	

:: (1/1) Parsing SRCINFO: c3
==> Making package: c3 0.5.1-1 (Mon 18 Mar 2024 07:35:40 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found c3.tar.gz
==> Validating source files with md5sums...
    c3.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: c3-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
c3 - exit status 1
```

Thanks for your time.

Cheers,

**Comment by nimaaskarian** [comment]
Hi,
So sorry I haven't checked the github issues lately.
I just tried installing c3 0.6.2-1 (latest) from the AUR now. It works.

Maybe this was a problem with first versions of the version bumping script (`bump-version.sh` or `release.sh`). I'm gonna check out and find out what was the cause, but either way, the problem doesn't seem to exist anymore.

Can you please check if it works fine for you and close the issue if it is?
Thanks!

**Comment by PierrickF** [comment]
Hi,

> So sorry I haven't checked the github issues lately.
No problem, you are providing open source work for free, and you don't owe anything to anyone. :)

Now, onto my issue.
Your comment made me spot the following line in the error message that I get:
```
 error downloading sources: /home/pierrick/.cache/yay/c3
```
So, there is nothing you could do if I was still pulling files from a local source. :D
I really was guilty of not reading correctly the error message, uh oh. D:

# Fix

I still had a local version of at least some files (I am not that familiar with the details of Yay or Cargo), so deleting them and running the installation command worked like a charm.

```
rm -rf /home/YOUR_USERNAME/.cache/yay/c3
yay -S c3
```

Thanks for your time.
